apiVersion : apps/v1
	kind: Deployment
	metadata:
	  name: sauravcluster 
	spec:
	  replicas: 1
	  selector:
	    matchLabels:
	      app: sauravcluster
	  template:
	    metadata:
	      labels:
	        app: sauravcluster 
	    spec:
	      containers:
	        - name: sauravcluster 
	          image: sauravclusteracr.azurecr.io/sauravcluster
	          ports:
	          - containerPort: 80